### ISSUE TITLE
Use reloc32short

### ISSUE THREAD

**Issue by polluks** [shred/patchwork#3]
If you use reloc32short you don't need the 2.04 check anymore.
https://eab.abime.net/showpost.php?p=1463979&postcount=19

**Comment by shred** [comment]
What 2.04 check do you mean?

**Comment by polluks** [comment]
https://github.com/shred/patchwork/blob/bde825aa3532c8ab1c2954ab7a01eb9a0872cc3c/src/Main.s#L35
This new hunk will deny execution below 2.04.

**Comment by shred** [comment]
Good idea! Fixed in 7ed431e. Thank you.
