### ISSUE TITLE
Possibility to "pause" PatchWork without stopping/restarting it

### ISSUE THREAD

**Issue by tygre-chingu** [shred/patchwork#5]
Hi again!
Now that I found that Cubic IDE generates all these "hits" for RectFill() (and other programs in other libraries, like MiamiDX for CreateIORequest()), I'd like to pause PatchWork :-) Right now, I start PatchWork along with other debug-related programs, like MuForce, MungWall, Sashimi... I could certainly add something in ToolsDaemon but I wonder, wouldn't be cool if PatchWork had an ARexx port that would listen to some command like "RUN"/"STOP" or "PAUSE"? 
Maybe it's a sledgehammer to crush a nut? If not, I could maybe try to implement that a send you a pull request?
Cheers!

**Comment by shred** [comment]
Yes, an ARexx port just for a pause function would probably be too big. :smile: I'm also not sure how I would implement the pause. If it would just pause the output, options like `DEADLY` would still be effective. It would be better to remove the patches in pause mode, and apply them again when the pause is ended. But that's the same like sending CTRL-C to PatchWork to "pause" it, and then just start it again.

MuForce and Mungwall also offer no pause switch, by the way. :wink:

I hope it's okay when I close this issue.
